[package]
name = "zero_sum"
version = "1.3.0"
authors = ["Chris Foster <cdbfoster@gmail.com>"]
license = "GPL-3.0"
description = "An analysis engine for zero-sum games with game implementations."
repository = "https://github.com/cdbfoster/zero_sum"
readme = "README.md"
documentation = "https://cdbfoster.github.io/doc/zero_sum"
keywords = ["zero-sum", "game", "chess", "tak", "tic-tac-toe"]
edition = "2015"

[features]
with_all = ["with_tak", "with_tak_ann", "with_tic_tac_toe"]
with_tak = []
with_tak_ann = ["with_tak", "blas", "rusqlite"]
with_tic_tac_toe = []

[dependencies]
blas = { version = "0.15.3", optional = true }
fnv = "1.0"
lazy_static = "1"
rand = "0.8"
rand_core = "0.6"
rusqlite = { version = "0.10", optional = true }

[[bin]]
name = "tak_ann_bootstrap_evaluator"
required-features = ["with_tak_ann"]

[[bin]]
name = "tak_ann_playtest"
required-features = ["with_tak_ann"]

[[bin]]
name = "tak_ann_sample_evaluations"
required-features = ["with_tak_ann"]

[[bin]]
name = "tak_ann_train_evaluator"
required-features = ["with_tak_ann"]

[[bin]]
name = "tak_ann_training_positions"
required-features = ["with_tak_ann"]

[[example]]
name = "tak_opening"
required-features = ["with_tak"]

[[example]]
name = "tic_tac_toe"
required-features = ["with_tic_tac_toe"]
